# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resouces/videothumbnailer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 924)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nrOfMarkedFrames = QtWidgets.QLabel(self.centralwidget)
        self.nrOfMarkedFrames.setGeometry(QtCore.QRect(190, 540, 99, 24))
        self.nrOfMarkedFrames.setObjectName("nrOfMarkedFrames")
        self.marksTreeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.marksTreeWidget.setGeometry(QtCore.QRect(240, 580, 411, 241))
        self.marksTreeWidget.setItemsExpandable(True)
        self.marksTreeWidget.setExpandsOnDoubleClick(True)
        self.marksTreeWidget.setObjectName("marksTreeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.marksTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.marksTreeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.videoFrame = QtWidgets.QFrame(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(10, 40, 441, 271))
        self.videoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoFrame.setObjectName("videoFrame")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 460, 567, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonStop = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.horizontalLayout.addWidget(self.pushButtonStop)
        self.pushButtonPlayPause = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPlayPause.setObjectName("pushButtonPlayPause")
        self.horizontalLayout.addWidget(self.pushButtonPlayPause)
        self.pushButtonStep = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonStep.setObjectName("pushButtonStep")
        self.horizontalLayout.addWidget(self.pushButtonStep)
        self.pushButtonMark = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMark.setObjectName("pushButtonMark")
        self.horizontalLayout.addWidget(self.pushButtonMark)
        self.videoName = QtWidgets.QLabel(self.centralwidget)
        self.videoName.setGeometry(QtCore.QRect(10, 10, 961, 24))
        self.videoName.setObjectName("videoName")
        self.pushButtonTest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTest.setGeometry(QtCore.QRect(670, 770, 125, 34))
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.marksListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.marksListWidget.setGeometry(QtCore.QRect(10, 580, 221, 241))
        self.marksListWidget.setObjectName("marksListWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 540, 171, 24))
        self.label.setObjectName("label")
        self.labelDebugInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelDebugInfo.setGeometry(QtCore.QRect(660, 680, 441, 21))
        self.labelDebugInfo.setObjectName("labelDebugInfo")
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(910, 320, 125, 34))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 330, 91, 24))
        self.label_2.setObjectName("label_2")
        self.labelImageGeometry = QtWidgets.QLabel(self.centralwidget)
        self.labelImageGeometry.setGeometry(QtCore.QRect(710, 330, 99, 24))
        self.labelImageGeometry.setObjectName("labelImageGeometry")
        self.labelMontageArea = QtWidgets.QLabel(self.centralwidget)
        self.labelMontageArea.setGeometry(QtCore.QRect(610, 20, 431, 241))
        self.labelMontageArea.setText("")
        self.labelMontageArea.setObjectName("labelMontageArea")
        self.sliderVideoPosition = QtWidgets.QSlider(self.centralwidget)
        self.sliderVideoPosition.setGeometry(QtCore.QRect(0, 320, 451, 22))
        self.sliderVideoPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVideoPosition.setObjectName("sliderVideoPosition")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(340, 520, 211, 36))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonDeleteMark = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonDeleteMark.setObjectName("pushButtonDeleteMark")
        self.horizontalLayout_2.addWidget(self.pushButtonDeleteMark)
        self.pushButtonClearMarks = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonClearMarks.setObjectName("pushButtonClearMarks")
        self.horizontalLayout_2.addWidget(self.pushButtonClearMarks)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 350, 431, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.currentTime = QtWidgets.QLabel(self.layoutWidget2)
        self.currentTime.setObjectName("currentTime")
        self.horizontalLayout_3.addWidget(self.currentTime)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.currentTimeMs = QtWidgets.QLabel(self.layoutWidget2)
        self.currentTimeMs.setObjectName("currentTimeMs")
        self.horizontalLayout_3.addWidget(self.currentTimeMs)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.videoDuration = QtWidgets.QLabel(self.layoutWidget2)
        self.videoDuration.setObjectName("videoDuration")
        self.horizontalLayout_3.addWidget(self.videoDuration)
        self.buttonAddChapter = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAddChapter.setGeometry(QtCore.QRect(980, 510, 125, 34))
        self.buttonAddChapter.setObjectName("buttonAddChapter")
        self.lineEditChapterTitel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditChapterTitel.setGeometry(QtCore.QRect(690, 550, 411, 32))
        self.lineEditChapterTitel.setObjectName("lineEditChapterTitel")
        self.listChapters = QtWidgets.QListWidget(self.centralwidget)
        self.listChapters.setGeometry(QtCore.QRect(650, 380, 451, 121))
        self.listChapters.setObjectName("listChapters")
        self.textEditChapterDescription = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEditChapterDescription.setGeometry(QtCore.QRect(690, 590, 411, 91))
        self.textEditChapterDescription.setObjectName("textEditChapterDescription")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFileOpen = QtWidgets.QAction(MainWindow)
        self.actionFileOpen.setObjectName("actionFileOpen")
        self.menuFile.addAction(self.actionFileOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nrOfMarkedFrames.setText(_translate("MainWindow", "nrOfMarkedFrames"))
        self.marksTreeWidget.headerItem().setText(0, _translate("MainWindow", "Chapter"))
        self.marksTreeWidget.headerItem().setText(1, _translate("MainWindow", "Frames"))
        __sortingEnabled = self.marksTreeWidget.isSortingEnabled()
        self.marksTreeWidget.setSortingEnabled(False)
        self.marksTreeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "New Item"))
        self.marksTreeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.marksTreeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "New Item"))
        self.marksTreeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.marksTreeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.pushButtonPlayPause.setText(_translate("MainWindow", "Play"))
        self.pushButtonPlayPause.setShortcut(_translate("MainWindow", "Space", " "))
        self.pushButtonStep.setText(_translate("MainWindow", "Step"))
        self.pushButtonStep.setShortcut(_translate("MainWindow", "."))
        self.pushButtonMark.setText(_translate("MainWindow", "Mark"))
        self.pushButtonMark.setShortcut(_translate("MainWindow", "M"))
        self.videoName.setText(_translate("MainWindow", "Video name"))
        self.pushButtonTest.setText(_translate("MainWindow", "Test mis"))
        self.label.setText(_translate("MainWindow", "Marked frames:"))
        self.labelDebugInfo.setText(_translate("MainWindow", "Debug info"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.label_2.setText(_translate("MainWindow", "Preview:"))
        self.labelImageGeometry.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonDeleteMark.setText(_translate("MainWindow", "Delete"))
        self.pushButtonDeleteMark.setShortcut(_translate("MainWindow", "Del"))
        self.pushButtonClearMarks.setText(_translate("MainWindow", "Clear all"))
        self.currentTime.setText(_translate("MainWindow", "currentTime"))
        self.currentTimeMs.setText(_translate("MainWindow", "currentMs"))
        self.videoDuration.setText(_translate("MainWindow", "duration"))
        self.buttonAddChapter.setText(_translate("MainWindow", "Add Chapter"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionFileOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

